# Dictionary of saved presets.
# You can edit the database manually, but be mindful
# not to disrupt the syntax of round (), square [] and curly brackets{}.

dict_of_presets = {
    'beige - darker side': {   'colors': [   (152, 132, 92),
                                             (124, 104, 72),
                                             (176, 156, 108),
                                             (0, 0, 0),
                                             (0, 0, 0)],
                               'probabilities': [92, 5, 3, 0, 0]},
    'brown building - dark side': {   'colors': [   (116, 68, 40),
                                                    (100, 40, 20),
                                                    (88, 52, 12),
                                                    (0, 0, 0),
                                                    (0, 0, 0)],
                                      'probabilities': [95, 3, 2, 0, 0]},
    'brown building - light side': {   'colors': [   (164, 96, 64),
                                                     (140, 76, 64),
                                                     (124, 104, 72),
                                                     (0, 0, 0),
                                                     (0, 0, 0)],
                                       'probabilities': [90, 5, 5, 0, 0]},
    'grey building - darker side': {   'colors': [   (116, 116, 116),
                                                     (132, 140, 152),
                                                     (100, 100, 100),
                                                     (0, 0, 0),
                                                     (0, 0, 0)],
                                       'probabilities': [96, 2, 2, 0, 0]},
    'grey building - light side': {   'colors': [   (148, 148, 148),
                                                    (168, 168, 168),
                                                    (132, 132, 132),
                                                    (0, 0, 0),
                                                    (0, 0, 0)],
                                      'probabilities': [95, 3, 2, 0, 0]},
    'pinkish - light side': {   'colors': [   (168, 92, 76),
                                              (140, 76, 64),
                                              (184, 108, 88),
                                              (0, 0, 0),
                                              (0, 0, 0)],
                                'probabilities': [70, 15, 15, 0, 0]},
    'snow - flat roof': {   'colors': [   (200, 236, 248),
                                          (180, 220, 236),
                                          (224, 244, 252),
                                          (252, 252, 252),
                                          (0, 0, 0)],
                            'probabilities': [43, 29, 24, 4, 0]},
    'snow - sloped to front - dark': {   'colors': [   (132, 188, 216),
                                                       (180, 220, 236),
                                                       (116, 172, 192),
                                                       (88, 152, 172),
                                                       (0, 0, 0)],
                                         'probabilities': [70, 15, 14, 1, 0]},
    'snow - sloped to front - light': {   'colors': [   (200, 236, 248),
                                                        (180, 220, 236),
                                                        (224, 244, 252),
                                                        (0, 0, 0),
                                                        (0, 0, 0)],
                                          'probabilities': [61, 23, 16, 0, 0]},
    'white building - dark side': {   'colors': [   (168, 168, 168),
                                                    (200, 200, 200),
                                                    (132, 132, 132),
                                                    (0, 0, 0),
                                                    (0, 0, 0)],
                                      'probabilities': [95, 2, 3, 0, 0]},
    'white building - light side': {   'colors': [   (200, 200, 200),
                                                     (232, 232, 232),
                                                     (168, 168, 168),
                                                     (0, 0, 0),
                                                     (0, 0, 0)],
                                       'probabilities': [90, 5, 5, 0, 0]}}